### ISSUE TITLE
the big refactor plan for the refactoring

### ISSUE THREAD

**Issue by fommil** [scala-ide/scala-refactoring#129]
@mlangc @xeno-by @smarter @sschaef @dragos @rorygraves (please add more as I don't know all handles)

Just to summarise what we discussed.
1. a lot of refactorings currently don't work. We are happy for the next release to remove all but: "rename", "organize [sic] imports" and "move class"
2. the scalac Tree API desugars the Trees such that printing the refactored trees is not an option. We are proposing to use the presentation compiler to produce the Tree diff, but then interpret the diff in a sugar-preserving Concrete Syntax Tree, such as the one produced by `scala.meta` (but we could also investigate using scalariform or https://github.com/lihaoyi/fastparse or bribe @sirthias with lots of beer to write it in parboiled2). Aka the "libre monad".

**Comment by sschaef** [comment]
Actually, it is not such a big refactor plan. Moving to scala.meta would be a big refactoring plan but we ended up with the conclusion that we won't do that since it is too unstable. We also came to the conclusion that we don't remove any refactorings but to mention in the README that they are not actively maintained. Matthias wants to try out the Libre Monad idea however. If there is a parser required we need to use scalariform, since we have to build all Scala dependencies against the nightlies of Scala itself.

**Comment by mlangc** [comment]
Well, the first thing I want to try is to implement rename refactorings without any tree transformations at all. The approach we discussed is:

1. Use the presentation compiler to find all places where the symbol that should be renamed occurs in the source code.
2. Do simple string replacements in exactly these places, instead of tree transformations and tree printing.
3. Eventually rename source files.

I think that this should work just fine - but maybe I'm missing something. If this approach should turn out to be successful, we might consider similar strategies for "Move Class".

* "Organize Imports" needs an update from the presentation compiler, that allows us to fix [#1001793](https://scala-ide-portfolio.assembla.com/spaces/scala-ide/tickets/1001793). This has been discussed with @dragos . A hybrid approach as suggested above could definitely make sense here: Use presentation compiler ASTs to find out which imports can be removed/have to be kept, but perform the actual transformation on a scalameta CST (concrete syntax tree). @wpopielarski what do you think?
* I'd rather not think too much about more advanced refactorings until we get the basics right.

As for unmaintained refactorings: We want to keep them in the library as @sschaef pointed out. They should however be dropped from Scala-IDE (are they included in ENSIME?), out of respect to our users ;-).

**Comment by fommil** [comment]
cool stuff! In terms of the unmaintained refactorings, I tend to agree with @mlangc that if they aren't stable we'd be happy just removing them. I'll create a ticket for that.

I thought the parser part of `scala.meta` was stable enough to use? I'd really love to write a parboiled2 parser for scala, but unfortunately it's not in my top 10 "paint" list and they tend to get fixed long before my top 10 "love to do" list :cry:

**Comment by sschaef** [comment]
On 02/14/2016 12:49 PM, Sam Halliday wrote:
>
> I thought the parser part of |scala.meta| was stable enough to use? 
> I'd really love to write a parboiled2 parser for scala, but 
> unfortunately it's not in my top 10 "paint" list and they tend to get 
> fixed long before my top 10 "love to do" list :cry:
>
We would have to compile it against every nightly of scalac, which adds 
additional complexity in our build infrastructure. Beside from that a 
parboiled2 parser for scala already exists, created by lihaoyi and paulp.

**Comment by xeno-by** [comment]
@sschaef The pb2 parser that you're referring to doesn't generate ASTs.

**Comment by fommil** [comment]
can you please link me to the parser? I thought howey wrote his own parser library for this

**Comment by sschaef** [comment]
It looks like they both removed the parser from their repos but I still have it on my own computer. I can send it to you but as Eugene said, the parser doesn't create a tree. Shouldn't be too difficult to add one though.

**Comment by fommil** [comment]
might be worth asking them where they moved the parser to

**Comment by fommil** [comment]
do you mean https://github.com/sirthias/parboiled2/tree/release-2.1/scalaParser/src ?

**Comment by xeno-by** [comment]
I think this is the most up-to-date parser: https://github.com/lihaoyi/fastparse/tree/master/scalaparse/shared/src/main/scala/scalaparse.

If you plan to create custom trees for scalaparse, you may want to consider integration with scala.meta trees. You could also try out scala.meta trees first to see whether the notion of CSTs will be useful for your purposes.

**Comment by fommil** [comment]
my preference would be to use `scala.meta` first, falling back to the parboiled2 or scalaparse implementations.

**Comment by wpopielarski** [comment]
I agree with you, Matthias. So first focusing on alluded three basic
refactorings: rename, move, organize imports and then rest. @dragos
mentioned about let call it elementary actions which could be chained in
more complex actions but I'm not so experienced and cannot take the opinion.
Generally I incline to your hybrid approach in next release. It would be
really good for Eugene too. You would be the testers for his work :). So up
to end of February (Scala IDE rel. 4.4) I fix organize imports in old
fashionable way and just after release we could start to refactor
refactoring with scalameta CST

**Comment by fommil** [comment]
@lihaoyi can your scala parser return a tree representation? Would it be possible to be able to provide a position in the source code and get back a lens that points at an element in the tree? Consider this use case: we know exactly which position of all variables that need to be renamed, and we would like to be able to provide them to a tree representation of the code, make the change, then write out the refactored version.

**Comment by fommil** [comment]
@xeno-by can `scala.meta` provide similar lenses?

**Comment by fommil** [comment]
@sirthius same question for the parboiled2 implementation

**Comment by sirthias** [comment]
Sorry for not following this discussion more closely, but here are my 2c regarding the pb2 Scala parser:
The work is almost entirely @lihaoyi and paulp's and the pb2 version is essentially unmaintained and probably not in very good shape.
If @lihaoyi has continued the work on the Scala parser in the context of his fastparse lib (as I assume) I'd definitely recommend to build on that one rather than pb2 for this project.

Without having any experience with fastparse myself it's my impression is that it is receiving more love from its authors than pb2 at this point, making it a better base for a large language parser like the one for Scala.
I do have plans for pb2 but very limited capacity for it right now, so, if you really want to put large weight on a parsing toolkit, pb2 might not be the best choice, unfortunately...

**Comment by lihaoyi** [comment]
Yeah the PB2 version is dead. The FastParse one is heavily used in Ammonite and Scalatex and other places and isn't going anywhere.

I'm not currently generating trees because I don't need them. Doing so would be straightforward, if slightly tedious, but it shouldn't require any novel techniques or problem solving. Someone just needs to define the 100 or so nodes that form the Scala Concrete Syntax Tree and put in the 100-200 `.map` calls to plumb them into Scalaparse.

The runtime perf will be worse than PB2 but the Quality of Life is much better and developer velocity probably higher

**Comment by lihaoyi** [comment]
ps. to answer the earlier question, no it does not currently track RangePositions, just like it doesn't even build an AST. Making it track 100% accurate RangePositions would be basically a bunch of grunt-work and isn't inherently difficult at all. Someone just needs to put a bunch of `Index` parsers before and after each node and plumb the resultant integers into where-ever they belong inside the AST

**Comment by fommil** [comment]
@lihaoyi just when I thought you were going to write your own scala compiler, you go and let me down.

**Comment by fommil** [comment]
A Google Summer of Code idea, we'll be submitting this via EPFL http://ensime.github.io/contributing/ideas/

**Comment by mlangc** [comment]
It might interest you that rename refactorings no longer do any tree printing at all: #133

**Comment by rorygraves** [comment]
Very cool stuff @mlangc

**Comment by fommil** [comment]
nice!!!!

**Comment by fommil** [comment]
@pavelfatin where is the IntelliJ CST code? I'd like to link to it from our proposal

**Comment by mlangc** [comment]
@fommil I'm not sure if I understand your SOC proposal: You mean implementing something like

    def findInCst(astNode: CompilerAstNode): Option[CstNode]

that would return `Some(x)` in all but a few corner cases? That could be quite useful for the refactoring library, if we take the hybrid approach discussed above. The reverse mapping

    def findClosestMatchInAst(cstNode: CstNode): Option[CompilerAstNode]

might also be of interest, but I don't have a specific use case for it in mind at the moment (although I'm almost sure that there are some).

@xeno-by Did I understand you correctly if I think that you are currently struggling with removing the `Option` from these transformations, so that you can enrich your CSTs appropriately?

**Comment by fommil** [comment]
Pretty much, but a lens would allow you to find it within your tree, and swap it out.

**Comment by mlangc** [comment]
Hmm, can you give me an example?

**Comment by fommil** [comment]
Well basically instead of returning an Option[Cst] it would return Option[CstLens] and Lens would have get/set on it.

**Comment by mlangc** [comment]
Ahh... makes sense to me now ;-).

**Comment by xeno-by** [comment]
@fommil Maybe you could mention the type signature in the proposal already?

**Comment by fommil** [comment]
Well
the idea would be to come up with another one (Cst, a sealed family of
case classes) which is preserving of the source code (several exist
already) and then provide a Lens something like

```scala
  // tree is a branch in the full AST
  // cst is the full CST for the compilation unit
  lens(tree: Tree, cst: Cst): Lens

  trait Lens {
    // get the source code preserving element referenced by the Tree
    def get: Cst

    // return a new full Cst for the compilation unit with this one part replaced
    def set(cst: Cst): Cst
  }
```

**Comment by mlangc** [comment]
Hmm, there are trees in the AST that cannot be easily matched to corresponding CST constructs. Run
```scala
case class Example(i: Int = 0, j: Int = 0) {
  def foo = copy(j = 1)
}
```
through `scalac -Xprint:4 Example.scala` and marvel at all the `<synthetic>` stuff to see what I mean. Thus I think that we would rather have
```scala
lens(tree: Tree, cst: Cst): Option[Lens]
```

**Comment by ShaneDelmore** [comment]
With ScalaSphere having just finished up is there now any plan to start using ScalaMeta/Scalafix for refactorings?

**Comment by fommil** [comment]
there is a GSoC and it's up to @mlangc to select it or not depending on the quality

**Comment by mlangc** [comment]
I've endorsed the proposal, so lets hope that it gets accepted by Google (I can't tell what the chances are though).
